server {
    listen 80;
    client_max_body_size 200m;
    resolver 127.0.0.11 valid=10s;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /api/ {
        set $backend http://backend:3000;
        rewrite ^/api/(.*)$ /$1 break;
        proxy_pass $backend;
        proxy_request_buffering off;
        proxy_buffering off;
        proxy_read_timeout 300s;
    }
}
